---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/rootfs

inputs:
- name: turbo
- name: bbr

outputs:
- name: backups

run:
  path: turbo/ci/backup-restore/tasks/backup-jumpbox/task.sh

params:
  JUMPBOX_SSH_KEY:
  JUMPBOX_SSH_USER:
  BOSH_STATE_FOLDER: