---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: turbo-devel
  - name: bosh-deployment
  - name: stemcell
  - name: release

# params:
#   BOSH_ENVIRONMENT: ((bosh_host))
#   BOSH_CA_CERT: ((bosh_ca_cert))
#   BOSH_CLIENT: ((bosh_admin.username))
#   BOSH_CLIENT_SECRET: ((bosh_admin.password))

outputs:
  - name: compiled-release

run:
  path: turbo-devel/ci/compiled-releases/tasks/export-release/task.sh
