---
azs:
- name: z1
  cloud_properties: {zone: ${tf_gcp_zone_1}}

vm_types:
- name: default
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: concourse
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: credhub
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

disk_types:
- name: default
  disk_size: 3000
- name: db
  disk_size: 10240
- name: 10GB
  disk_size: 10240

networks:
- name: concourse
  type: manual
  subnets:
  - range:   ${tf_concourse_subnet_range}
    gateway: ${tf_concourse_subnet_gateway}
    dns:     [8.8.8.8, 8.8.4.4]
    static: [${cidrhost(tf_concourse_subnet_range,5)},${cidrhost(tf_concourse_subnet_range,6)},${cidrhost(tf_concourse_subnet_range,7)},${cidrhost(tf_concourse_subnet_range,8)}]
    azs:     [z1]
    cloud_properties:
      network_name: ${tf_bootstrap_network_name}
      subnetwork_name: ${tf_concourse_subnet_name}
      ephemeral_external_ip: false
      tags: [${tf_env_name}-internal, ${tf_env_name}-nat]

vm_extensions:
- name: concourse-web
  cloud_properties:
    backend_service:
      name: ${tf_concourse_web_backend_group}
- name: credhub
  cloud_properties:
    backend_service:
      name: ${tf_credhub_backend_group}
- name: uaa
  cloud_properties:
    backend_service:
      name: ${tf_uaa_backend_group}

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: concourse