platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/rootfs}
  
inputs:
  - name: turbo-devel
  - name: terraform
  - name: turbo-devel-ci

run:
  path: turbo-devel-ci/ci/devel-testing/tasks/run-tests/task.sh
  