---
azs:
- name: z1
  cloud_properties: {availability_zone: ((aws_az1))}

vm_types:
- name: db-small
  cloud_properties:
    instance_type: t2.small
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true
- name: db-medium
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true
- name: db-large
  cloud_properties:
    instance_type: m4.large
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true
- name: db-xlarge
  cloud_properties:
    instance_type: m4.xlarge
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true
- name: db-2xlarge
  cloud_properties:
    instance_type: m4.2xlarge
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true
- name: db-4xlarge
  cloud_properties:
    instance_type: m4.4xlarge
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true
- name: db-10xlarge
  cloud_properties:
    instance_type: m4.10xlarge
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true
- name: db-16xlarge
  cloud_properties:
    instance_type: m4.16xlarge
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true

- name: credhub
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true

- name: metrics
  cloud_properties:
    instance_type: t2.small
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true

- name: concourse-web-small
  cloud_properties:
    instance_type: t2.small
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
- name: concourse-web-medium
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
- name: concourse-web-large
  cloud_properties:
    instance_type: t2.large
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
- name: concourse-web-xlarge
  cloud_properties:
    instance_type: t2.xlarge
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
- name: concourse-web-2xlarge
  cloud_properties:
    instance_type: t2.2xlarge
    ephemeral_disk:
      size: 20_000
      type: gp2
      encrypted: true
- name: worker-medium
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
- name: worker-large
  cloud_properties:
    instance_type: m4.large
    spot_bid_price: 0.13 # on-demand price: 0.111
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
- name: worker-xlarge
  cloud_properties:
    instance_type: m4.xlarge
    spot_bid_price: 0.27 # on-demand price: 0.222
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
- name: worker-2xlarge
  cloud_properties:
    instance_type: m4.2xlarge
    spot_bid_price: 0.53 # on-demand price: 0.444
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
- name: worker-4xlarge
  cloud_properties:
    instance_type: m4.4xlarge
    spot_bid_price: 1.07 # on-demand price: 0.888
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
- name: worker-10xlarge
  cloud_properties:
    instance_type: m4.10xlarge
    spot_bid_price: 2.67 # on-demand price: 2.22
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true
- name: worker-16xlarge
  cloud_properties:
    instance_type: m4.16xlarge
    spot_bid_price: 4.26 # on-demand price: 3.55
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 200_000
      type: gp2
      encrypted: true

- name: compilation
  cloud_properties:
    instance_type: m4.large
    spot_bid_price: 0.13 # on-demand price: 0.111
    spot_ondemand_fallback: true
    ephemeral_disk:
      size: 10_000
      type: gp2
      encrypted: true

disk_types:
- name: 10G
  cloud_properties:
    type: gp2
    encrypted: true
  disk_size: 10240
- name: 25G
  cloud_properties:
    type: gp2
    encrypted: true
  disk_size: 25600
- name: 50G
  cloud_properties:
    type: gp2
    encrypted: true
  disk_size: 51200
- name: 100G
  cloud_properties:
    type: gp2
    encrypted: true
  disk_size: 102400
- name: 250G
  cloud_properties:
    type: gp2
    encrypted: true
  disk_size: 256000
- name: 500G
  cloud_properties:
    type: gp2
    encrypted: true
  disk_size: 512000
- name: 1000G
  cloud_properties:
    type: gp2
    encrypted: true
  disk_size: 1024000

networks:
- name: bosh
  type: manual
  subnets:
  - range:   ((bosh_subnet_range))
    gateway: ((bosh_subnet_gateway))
    dns:     [169.254.169.253]
    static: ((bosh_network_static_ips))
    reserved: ((bosh_network_reserved_ips))
    azs:     [z1]
    cloud_properties:
      subnet: ((bosh_subnet_id))
- name: concourse
  type: manual
  subnets:
  - range:   ((az1_concourse_subnet_range))
    gateway: ((az1_concourse_subnet_gateway))
    dns:     [169.254.169.253]
    static: ((az1_concourse_network_static_ips))
    reserved: ((az1_concourse_network_reserved_ips))
    azs:     [z1]
    cloud_properties:
      subnet: ((az1_concourse_subnet_id))

vm_extensions:
- name: concourse-web
  cloud_properties:
    elbs:
    - ((concourse_web_backend_group))
- name: credhub
  cloud_properties:
    elbs:
    - ((credhub_backend_group))
    - ((uaa_backend_group))
- name: metrics
  cloud_properties:
    elbs:
    - ((metrics_backend_group))

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: bosh