---
resources:
- name: turbo-ci
  type: git
  source:
    uri: git@gitlab.com:RomRider/turbo.git
    branch: devel
    private_key: ((ssh_key_gitlab))
    paths: [ci/*]

- name: night-2am
  type: time
  source:
    start: 2:00 AM
    stop: 3:00 AM

- name: manualtrigger
  type: time           # technique to trigger and propagate manual execution through pipeline
  source:
    interval: 1m

- name: bucket-jumpbox
  type: gcs-bucket
  source:
    bucket: ((backups_bucket_name))
    json_key: ((gcp_key))
    regexp: "jumpbox-backup-.*.tgz"

- name: bucket-director
  type: gcs-bucket
  source:
    bucket: ((backups_bucket_name))
    json_key: ((gcp_key))
    regexp: "director-backup-.*.tar"

- name: bucket-deployment
  type: gcs-bucket
  source:
    bucket: ((backups_bucket_name))
    json_key: ((gcp_key))
    regexp: ".*-backup-.*.tar"

resource_types:
  - name: gcs-bucket
    type: docker-image
    source:
      repository: frodenas/gcs-resource

jobs:
- name: Manual Trigger
  plan:
  - get: manualtrigger
    trigger: false

- name: backup-jumpbox
  plan:
  - aggregate:
    - get: manualtrigger
      trigger: true
      passed:
      - Manual Trigger
    - get: turbo-ci
    - get: night-2am
  - task: download-bbr
    file: turbo-ci/ci/backup-restore/tasks/download-bbr/task.yml
    input_mapping:
      turbo: turbo-ci
  - task: backup-jumpbox
    file: turbo-ci/ci/backup-restore/tasks/backup-jumpbox/task.yml
    input_mapping:
      turbo: turbo-ci
    params:
      JUMPBOX_HOST: ((jumpbox_host))
      JUMPBOX_SSH_KEY: ((jumpbox_ssh_key.private_key))
      JUMPBOX_SSH_USER: ((jumpbox_user))
      BOSH_STATE_FOLDER: /data/bosh-state/
  - put: bucket-jumpbox
    params:
      file: "backups/*.tgz"
    
      
- name: backup-director
  plan:
  - aggregate:
    - get: manualtrigger
      trigger: true
      passed:
      - Manual Trigger
    - get: turbo-ci
    - get: night-2am
  - task: download-bbr
    file: turbo-ci/ci/backup-restore/tasks/download-bbr/task.yml
    input_mapping:
      turbo: turbo-ci
  - task: backup-director
    file: turbo-ci/ci/backup-restore/tasks/backup-director/task.yml
    input_mapping:
      turbo: turbo-ci
    params:
      BOSH_DIRECTOR_HOST: ((bosh_host))
      BOSH_SSH_USER: ((bosh_ssh_user))
      BOSH_SSH_KEY: ((bosh_ssh_key.private_key))
  - put: bucket-director
    params:
      file: "backups/*.tar"

- name: backup-ucc
  plan:
  - aggregate:
    - get: manualtrigger
      trigger: true
      passed:
      - Manual Trigger
    - get: turbo-ci
    - get: night-2am
  - task: download-bbr
    file: turbo-ci/ci/backup-restore/tasks/download-bbr/task.yml
    input_mapping:
      turbo: turbo-ci
  - task: backup-deployment
    file: turbo-ci/ci/backup-restore/tasks/backup-deployment/task.yml
    input_mapping:
      turbo: turbo-ci
    params:
      BOSH_DIRECTOR_HOST: ((bosh_host))
      BOSH_BBR_USERNAME: ((bosh_admin.username))
      BOSH_BBR_PASSWORD: ((bosh_admin.password))
      BOSH_CA_CERT: ((bosh_ca_cert.certificate))
      DEPLOYMENT_NAME: ((env_name))-ucc
      JUMPBOX_HOST: ((jumpbox_host))
      JUMPBOX_SSH_KEY: ((jumpbox_ssh_key.private_key))
      JUMPBOX_SSH_USER: ((jumpbox_user))
  - put: bucket-deployment
    params:
      file: "backups/*.tgz"