---
resources:
- name: this-repo
  type: git
  source:
    uri: git@gitlab.com:RomRider/turbo.git
    branch: devel
    private_key: ((ssh_key_gitlab))

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git
    branch: master

  # releases

- name: concourse-release
  type: bosh-io-release
  source:
    repository: concourse/concourse

- name: credhub-release
  type: bosh-io-release
  source:
    repository: pivotal-cf/credhub-release

- name: uaa-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/uaa-release

- name: garden-runc-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

- name: postgres-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/postgres-release

- name: bbr-sdk-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/backup-and-restore-sdk-release

- name: grafana-release
  type: bosh-io-release
  source:
    repository: vito/grafana-boshrelease

- name: influxdb-release
  type: bosh-io-release
  source:
    repository: vito/influxdb-boshrelease

- name: riemann-release
  type: bosh-io-release
  source:
    repository: xoebus/riemann-boshrelease

# stemcells

- name: ubuntu-trusty-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version_family: "3468"

# outputs

- name: compiled-releases
  type: gcs-bucket
  source:
    bucket: &compiled_bucket_name "bosh-compiled-release-tarballs"
    json_key: ((gcp_key))
    regexp: ".*-(\\d+).tgz"

resource_types:
  - name: gcs-bucket
    type: docker-image
    source:
      repository: frodenas/gcs-resource

jobs:
  - name: compile-uaa-release
    plan:
      - aggregate:
          - get: this-repo
          - get: bosh-deployment
          - get: uaa-release
            trigger: true
          - get: ubuntu-trusty-stemcell
            trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: uaa-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-credhub-release
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: credhub-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: credhub-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-bbr-sdk-release
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: bbr-sdk-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bbr-sdk-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-bbr-sdk-release-stemcell-director
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: bbr-sdk-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
          version:
            version: "3468.21"
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: bbr-sdk-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-garden-runc-release
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: garden-runc-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: garden-runc-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-postgres-release
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: postgres-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: postgres-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-concourse-release
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: concourse-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: concourse-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-grafana-release
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: grafana-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: grafana-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-influxdb-release
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: influxdb-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: influxdb-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))

  - name: compile-riemann-release
    plan:
      - aggregate:
        - get: this-repo
        - get: bosh-deployment
        - get: riemann-release
          trigger: true
        - get: ubuntu-trusty-stemcell
          trigger: true
      - task: export-release
        file: this-repo/ci/compiled-releases/tasks/export-release.yml
        privileged: true
        input_mapping:
          stemcell: ubuntu-trusty-stemcell
          release: riemann-release
      - put: compiled-releases
        params:
          file: "compiled-release/*.tgz"
      - task: make-public
        file: this-repo/ci/compiled-releases/tasks/make-public.yml
        params:
          GCP_BUCKET: *compiled_bucket_name
          GCP_KEY: ((gcp_key))
